name: kib_utils
description: A Dart package providing utility classes including Result for error handling.
version: 1.0.0
repository: https://github.com/kibmuikia/kib_utils

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
